### ISSUE TITLE
Added auto-stay when room size > 4000

### ISSUE THREAD

**Issue by jer-lim** [keythkatz/Robin-Autovoter#10]
Agreed? If we ever get there again I think it's time to immortalise the chat. I've added the toggeable code, but it can be removed.

**Comment by jhon** [comment]
No reason to not have it. The only thing I suggest is turning it off by default so someone doesn't get it by accident.

**Comment by jer-lim** [comment]
My reasoning behind leaving it on by default is that we won't ever get enough users staying if we reach that point. Right now it's highly unlikely we'd go beyond that, since 4000 is at least 12 hours away right now.

**Comment by jhon** [comment]
Yeah, that's a fair point. Via the leaderboard, we're only tracking 5142 total users across 13 rooms.

**Comment by jhon** [comment]
Agreed.
