### ISSUE TITLE
Create version that only sends statistics

### ISSUE THREAD

**Issue by ABruihler** [keythkatz/Robin-Autovoter#17]
I'm using another script, but I still want to be able to contribute to the statistics page.  Could a version of Robin-Autovoter be created that only sends the statistics, so the user can use another script of their choice for the other functionality?

**Comment by jhon** [comment]
Created a userscript for ya over in the robintracker repo: https://raw.githubusercontent.com/jhon/robintracker/master/robintracker.user.js

I'll add instructions to the leaderboard.

**Comment by ABruihler** [comment]
Thanks!  Looks good.
