### ISSUE TITLE
Spam Text

### ISSUE THREAD

**Issue by Nullception** [keythkatz/Robin-Autovoter#2]
With more than one or two autovoters in the room, the message gets a little spammy. Can you have the script check if the autovoter message exists in the last 100 posts or so?

**Comment by Yantrio** [comment]
+1 I agree, it's getting a bit silly to keep seeing posts spammed.

**Comment by TobiTenno** [comment]
+1 disable it from constantly posting info

make it alert instead.

especially as this grows, take it up to scanning the last thousand or so for autovoter text.

**Comment by akmattb** [comment]
i dont think the .2 chance of posting is working... i have seen my page post on it almost every time.

**Comment by jer-lim** [comment]
Disabling link spam completely in next version (1.10)
