### ISSUE TITLE
Tracking API

### ISSUE THREAD

**Issue by cyberbalsa** [keythkatz/Robin-Autovoter#4]
I propose a tracking API, I can do the data store if you want to include it, something where we can put in a API key I provide and it will do a GET request to a URL, I can write the back end if you include it in your script.

**Comment by jer-lim** [comment]
Anything goes

**Comment by cyberbalsa** [comment]
could you send data to https://jrwr.space/robin/track.php?id={FIRST TEN OF
ROOM}&ab={ABANDON VOTE}&st={STAY}&gr={GROW}&nv={NOVOTE}&count={ROOM COUNT}

it will just respond with the text OK

and just send the total every X seconds you think is good and ill store and graph the data

**Comment by jhon** [comment]
I was intending to do this this morning. It'll be much easier if I'm not writing the backend. I should be able to whip this up in the next 15min or so

**Comment by cyberbalsa** [comment]
Cool! Ya I'm going to shove it into Redis for now and work on processing
the data, Ill provide a simple page to view the raw data for now.

**Comment by jer-lim** [comment]
XMLHttpRequest cannot load https://jrwr.space/robin/track.php?id=buKercNirk&ab=0&st=24&gr=5&nv=0&count=29. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.reddit.com' is therefore not allowed access.

You'll need to add that.

**Comment by jer-lim** [comment]
I've set it to send data every 10 seconds.

**Comment by cyberbalsa** [comment]
Sorry, it has been fixed

**Comment by jhon** [comment]
The data is only being pulled every 60s so there is no reason to update it further than that. #5 will pull statistics only when it goes through the update loop. It also adds a configuration option to the widgets so you can disable statistics tracking if you're lame.

**Comment by cyberbalsa** [comment]
Awesome, Also if you want to do some javascript graphing foo, and you know
a little PHP i can take any code you want to throw it at the database, all
updates are being stored. so like a predictor of what room will merge into
what

**Comment by cyberbalsa** [comment]
Here is how I'm storing the data in MySQL for now

"id","room","abandon","stay","grow","novote","count","timestamp","ip"
"28","PM_orsnayg","0","0","0","7","7","1459622080","129.7.106.XX"
"29","KolaanziTh","2","21","291","0","314","1459622081","65.28.80.XX"

**Comment by jhon** [comment]
Is there a repo setup?

**Comment by cyberbalsa** [comment]
Na its just a script I slapped together, mostly just a ingest script with
some checking, Ill be making graphs and data processors for now its just
being stored in bulk

**Comment by jhon** [comment]
I'm going to start reporting formation time and reap time as ft and rt. Let me know when you have a simple leaderboard setup.

**Comment by cyberbalsa** [comment]
I do!

http://jrwr.space/robin/table.php

its a very basic SQL Statement but it works

**Comment by jer-lim** [comment]
Very nice. Post it to /r/robintracking, and mention the script somewhere!

**Comment by jhon** [comment]
Looks good. I updated the readme with a link

**Comment by jhon** [comment]
https://www.reddit.com/r/robintracking/comments/4d32vy/automated_leader_board/d1nbh55

You're also getting requests for data. I'd love to see a repo so people can contribute. From there we can write some API scripts for pulling data for other visualizations.

**Comment by cyberbalsa** [comment]
Ill create one now,

**Comment by cyberbalsa** [comment]
https://github.com/jrwr/robintracker

**Comment by jhon** [comment]
Awesome. Gonna close this issue for now. If you need anything added from the bot side, feel free to open another one.
