### ISSUE TITLE
Keeping track of STAY's

### ISSUE THREAD

**Issue by robert-lawrence** [keythkatz/Robin-Autovoter#9]
Hey! Thanks for automating this, I've been maintaining the reddit leaderboard since yesterday and we're trying to find chats larger than 50 who have voted stay. Does your script currently report that?

**Comment by jhon** [comment]
Since we're currently reporting stay information to the trackers, it'd be possible to run a query over the data to get your answer.

Are you looking for rooms that ended with over 50 stays or currently open rooms with over 50 stays? Do you just want a webpage displaying that info or an API?

**Comment by robert-lawrence** [comment]
A webpage would be nice, and rooms that ended in a stay vote with over 50 people in the room

**Comment by robert-lawrence** [comment]
*webpage

**Comment by jhon** [comment]
Yeah, sure thing. I don't have time in the next few hours, but I'll add it to https://github.com/jhon/robintracker later tonight.

**Comment by robert-lawrence** [comment]
thanks!

**Comment by jhon** [comment]
https://monstrouspeace.com/robintracker/stay.php

As the site mentions, this uses data we started collecting only late today so its only pretty recent. If you have other feature requests for the tracker, create an issue in https://github.com/jhon/robintracker
